version: '3.8'

services:
  whisper-hub:
    # Option 1: Use pre-built image (uncomment next line and comment build line)
    # image: sighadd/whisper-hub:latest
    # Option 2: Build locally (default)
    build: .
    container_name: whisper-hub
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Set this environment variable
      - PORT=8080
      - UPLOAD_MAX_SIZE=104857600  # 100MB
      - TEMP_DIR=/tmp/whisper-hub
    volumes:
      - whisper_hub_temp:/tmp/whisper-hub
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    security_opt:
      - no-new-privileges:true

volumes:
  whisper_hub_temp:
    driver: local